const common = require('./common');

module.exports = common({
  plugins: [
    'babel',
  ],
  extends: [
    'airbnb-base',
  ],
  rules: {
    'babel/no-unused-expressions': 'error',
    'import/no-commonjs': 'error',
    'jquery/no-ajax': 'error',
    'jquery/no-animate': 'error',
    'jquery/no-attr': 'error',
    'jquery/no-bind': 'error',
    'jquery/no-class': 'error',
    'jquery/no-clone': 'error',
    'jquery/no-closest': 'error',
    'jquery/no-css': 'error',
    'jquery/no-data': 'error',
    'jquery/no-deferred': 'error',
    'jquery/no-delegate': 'error',
    'jquery/no-each': 'error',
    'jquery/no-fade': 'error',
    'jquery/no-filter': 'error',
    'jquery/no-find': 'error',
    'jquery/no-global-eval': 'error',
    'jquery/no-has': 'error',
    'jquery/no-hide': 'error',
    'jquery/no-html': 'error',
    'jquery/no-in-array': 'error',
    'jquery/no-is': 'error',
    'jquery/no-map': 'error',
    'jquery/no-merge': 'error',
    'jquery/no-param': 'error',
    'jquery/no-parent': 'error',
    'jquery/no-parents': 'error',
    'jquery/no-parse-html': 'error',
    'jquery/no-prop': 'error',
    'jquery/no-proxy': 'error',
    'jquery/no-serialize': 'error',
    'jquery/no-show': 'error',
    'jquery/no-sizzle': 'error',
    'jquery/no-slide': 'error',
    'jquery/no-text': 'error',
    'jquery/no-toggle': 'error',
    'jquery/no-trigger': 'error',
    'jquery/no-trim': 'error',
    'jquery/no-val': 'error',
    'jquery/no-wrap': 'error',
    'no-unused-expressions': 'off',
  },
});
